version: '3.3'
services:
  k6:
    image: grafana/k6@sha256:a7c79af2b374c9a3afa8b0fae9ec2899277d066612029b7b0fcd2fcb724ba86f
    container_name: k6
    volumes:
      - '${PWD}/src:/scripts'
    environment:
      - API_SUBSCRIPTION_KEY=${sub_key}
      - VARS=/scripts/${env}.environment.json
      - TEST_TYPE=/scripts/test-types/${type}.json
      - K6_OUT=influxdb=http://nginx:8086/${db_name}
    command: run /scripts/${script}.js
    depends_on:
      - nginx

  nginx:
    image: nginx@sha256:ca871a86d45a3ec6864dc45f014b11fe626145569ef0e74deaffc95a3b15b430
    container_name: nginx
    volumes:
      - '${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - "8086:8086"
      - "80:80"

