apiVersion: v2
name: pagopa-afm-calculator
description: Microservice that handles calculation for pagoPA Advanced Fees Management
type: application
version: 0.1.0
appVersion: 0.0.0-1-NOD-690-config-cache-nodo-cfg-sync-implementazione-microservizio
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
