apiVersion: v2
name: pagopa-node-cfg-sync
description: Microservice that sync api-config-cache and standin configuration
type: application
version: 0.83.0
appVersion: 0.0.6-1-NOD-866-dev-src
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
